title = "Engine Configuration"

######### VERTEX ATTRIBUTE INFOS ######
[[vas]]
name     = "vertex_only"
position = { datatype = "float", num = 3 }

[[vas]]
name     = "vertex_normal"
position = { datatype = "float", num = 3 }
normal   = { datatype = "float", num = 3 }

[[vas]]
name     = "vertex_color"
position = { datatype = "float", num = 3 }
color    = { datatype = "float", num = 4 }

[[vas]]
name     = "vertex_uv"
position = { datatype = "float", num = 3 }
uv       = { datatype = "float", num = 2 }

[[vas]]
name     = "vertex_normal_color"
position = { datatype = "float", num = 3 }
normal   = { datatype = "float", num = 3 }
color    = { datatype = "float", num = 4 }

[[vas]]
name     = "vertex_normal_uvs"
position = { datatype = "float", num = 3 }
normal   = { datatype = "float", num = 3 }
uv       = { datatype = "float", num = 2 }

[[vas]]
name     = "terrain"
position = { datatype = "float", num = 3 }
normal   = { datatype = "float", num = 3 }
uv       = { datatype = "float", num = 2 }

[[vas]]
name     = "water"
position = { datatype = "float", num = 3 }
uv       = { datatype = "float", num = 2 }

########### SHADERS #################
[[shaders]]
name = "2dcolor"
vertex = "2dcolor.vert"
fragment = "2dcolor.frag"
va = "vertex_color"
is_2d = true

[[shaders]]
name = "2dtexture"
vertex = "2dtexture.vert"
fragment = "2dtexture.frag"
va = "vertex_uv"
is_2d = true

[[shaders]]
name = "3dtexture"
vertex = "3dtexture.vert"
fragment = "3dtexture.frag"
va = "vertex_normal_uvs"

[[shaders]]
name = "3dcube_texture"
vertex = "3dcube_texture.vert"
fragment = "3dcube_texture.frag"
va = "vertex_only"

[[shaders]]
name = "skybox"
vertex = "3dcube_texture.vert"
fragment = "3dcube_texture.frag"
va = "vertex_only"

[[shaders]]
name = "3d_pos_normal_color"
vertex = "3d_pos_normal_color.vert"
fragment = "3d_pos_normal_color.frag"
va = "vertex_normal_color"

[[shaders]]
name = "3d_pos_color"
vertex = "3d_pos_color.vert"
fragment = "3d_pos_color.frag"
va = "vertex_color"

[[shaders]]
name = "light"
vertex = "light.vert"
fragment = "light.frag"
va = "vertex_only"

[[shaders]]
name = "2dlight_uv"
vertex = "2dlight_uv.vert"
fragment = "2dlight_uv.frag"
va = "vertex_uv"
is_2d = true

[[shaders]]
name = "torch"
vertex = "torch.vert"
fragment = "torch.frag"
va = "vertex_uv"

############# letters

[[shaders]]
name = "hashtag"
vertex = "3d_hashtag.vert"
fragment = "3d_pos_normal_color.frag"
va = "vertex_normal_color"
instance_count = 3

[[shaders]]
name = "river"
vertex = "river.vert"
fragment = "3d_pos_normal_color.frag"
va = "vertex_normal"
instance_count = 4

[[shaders]]
name = "stair"
vertex = "stair.vert"
fragment = "stair.frag"
va = "vertex_normal"

[[shaders]]
name = "floor"
vertex = "floor.vert"
fragment = "3d_pos_normal_color.frag"
va = "vertex_normal_color"

[[shaders]]
name = "terrain"
vertex = "terrain.vert"
fragment = "terrain.frag"
va = "terrain"

[[shaders]]
name = "water"
vertex = "water.vert"
fragment = "water.frag"
va = "water"
