#ifndef __PREAMBLE_GLSL__
#define __PREAMBLE_GLSL__

// vertex attribute indices
#define VERTEX_ATTRIBUTE_INDEX_OF_POSITION 0
#define VERTEX_ATTRIBUTE_INDEX_OF_COLOR 1
#define VERTEX_ATTRIBUTE_INDEX_OF_UV 2

// uniforms
#define VIEW_MATRIX_UNIFORM_LOCATION 0
#define PROJECTION_MATRIX_UNIFORM_LOCATION 1

#endif // __PREAMBLE_GLSL__
