title = "Level 0"
background = [0.0, 0.0, 0.0]
camera_spherical_coords = [2.56, 6.6446330, 56.379040]

ambient = [0.0, 0.0, 0.0]
directional_light_diffuse = [0.0, 0.0, 1.0]
directional_light_specular = [0.0, 1.0, 0.0]
directional_light_direction = [-0.4, 0.0, 0.1]

[[resource]]
name = "building_skybox"
type = "texture:3dcube-RGB"
front = "sb_front.jpg"
right = "sb_right.jpg"
back = "sb_back.jpg"
left = "sb_left.jpg"
top = "sb_top.jpg"
bottom = "sb_bottom.jpg"

[[resource]]
name = "boring_cube"
type = "texture:3dcube-RGB"
front = "cube_front.jpg"
right = "cube_right.jpg"
back = "cube_back.jpg"
left = "cube_left.jpg"
top = "cube_top.jpg"
bottom = "cube_bottom.jpg"

[[resource]]
name = "container"
type = "texture:2d-RGB"
filename = "container.jpg"

[[resource]]
name = "Lava"
type = "texture:2d-RGBA"
filename = "lava.jpg"

[[resource]]
name = "RedX"
type = "texture:2d-RGBA"
filename = "redx.png"

[[resource]]
name = "InventorySlotEmpty"
type = "texture:2d-RGBA"
filename = "ui/inventory_slot_empty.png"

[[resource]]
name = "wall"
type = "texture:2d-RGB"
filename = "wall.jpg"

[[resource]]
name = "TextureAtlas"
type = "texture:2d-RGB"
filename = "TextureAtlas.jpg"

[[resource]]
name = "TargetReticle"
type = "texture:2d-RGBA"
filename = "circle_reticle.png"

[[resource]]
name = "TerrainFloor"
type = "texture:2d-RGB"
filename = "textures/TerrainFloor.jpg"
wrap = "repeat"
uvs = 10000

[[resource]]
name = "gun"
type = "texture:2d-RGB"
filename = "gun.png"

[[resource]]
name = "sword"
type = "texture:2d-RGB"
filename = "sword.png"

[[resource]]
name = "cloud"
type = "texture:2d-RGBA"
filename = "textures/cloud_cumulous_large.png"

[[resource]]
name = "sun"
type = "texture:2d-RGBA"
filename = "textures/sun.png"

[[resource]]
name = "sun_blue"
type = "texture:2d-RGBA"
filename = "textures/sun_blue.png"

[[resource]]
name = "TorchUI"
type = "texture:2d-RGBA"
filename = "ui/torch-icon.png"

[[resource]]
name = "test_icon"
type = "texture:2d-RGB"
filename = "test_icon.png"

###################################################################################################
[[tile]]
tile = "AT"
mesh = "at"
vshader = "3d_pos_normal_color"
color = [1.0, 1.0, 1.0, 1.0]
ambient = [1.0, 1.0, 1.0]
diffuse = [1.0, 1.0, 1.0]
specular = [1.0, 1.0, 1.0]
shininess = 1.0

[[tile]]
tile = "BAR"
mesh = "bar"
vshader = "3d_pos_normal_color"
color = [1.0, 1.0, 1.0, 1.0]
ambient = [1.0, 1.0, 1.0]
diffuse = [1.0, 1.0, 1.0]
specular = [1.0, 1.0, 1.0]
shininess = 1.0

[[tile]]
tile = "BRIDGE"
mesh = "equal"
vshader = "3d_pos_normal_color"
color = [1.0, 1.0, 1.0, 1.0]
ambient = [1.0, 1.0, 1.0]
diffuse = [1.0, 1.0, 1.0]
specular = [1.0, 1.0, 1.0]
shininess = 1.0

[[tile]]
tile = "DOOR"
mesh = "door"
vshader = "3d_pos_normal_color"
color = [1.0, 1.0, 1.0, 1.0]
ambient = [1.0, 1.0, 1.0]
diffuse = [1.0, 1.0, 1.0]
specular = [1.0, 1.0, 1.0]
shininess = 1.0

[[tile]]
tile = "FLOOR"
mesh = "plus"
vshader = "floor"
color = [1.0, 1.0, 1.0, 1.0]
ambient = [1.0, 1.0, 1.0]
diffuse = [1.0, 1.0, 1.0]
specular = [1.0, 1.0, 1.0]
shininess = 1.0

[[tile]]
tile = "RIVER"
mesh = "tilde"
vshader = "river"
color = [1.0, 1.0, 1.0, 1.0]
ambient = [0.1, 0.2, 1.0]
diffuse = [0.1, 0.3, 1.0]
specular = [0.2, 0.4, 1.0]
shininess = 1.0

[[tile]]
tile = "STAR"
mesh = "star"
vshader = "3d_pos_normal_color"
color = [1.0, 1.0, 1.0, 1.0]
ambient = [1.0, 1.0, 1.0]
diffuse = [1.0, 1.0, 1.0]
specular = [1.0, 1.0, 1.0]
shininess = 1.0

[[tile]]
tile = "STAIR_DOWN"
mesh = "stair_down"
vshader = "stair"
color = [1.0, 1.0, 1.0, 1.0]
ambient = [0.0, 1.0, 0.0]
diffuse = [0.0, 1.0, 0.0]
specular = [0.0, 1.0, 0.0]
shininess = 1.0

[[tile]]
tile = "STAIR_UP"
mesh = "stair_up"
vshader = "stair"
color = [1.0, 1.0, 1.0, 1.0]
ambient = [1.0, 0.0, 0.0]
diffuse = [1.0, 0.0, 0.0]
specular = [1.0, 0.0, 0.0]
shininess = 1.0

[[tile]]
tile = "TELEPORTER"
mesh = "teleporter"
vshader = "3d_pos_normal_color"
color = [1.0, 1.0, 1.0, 1.0]
ambient = [1.0, 1.0, 1.0]
diffuse = [1.0, 1.0, 1.0]
specular = [1.0, 1.0, 1.0]
shininess = 1.0

[[tile]]
tile = "WALL"
mesh = "hashtag"
vshader = "hashtag"
color = [1.0, 1.0, 1.0, 1.0]
ambient = [1.0, 1.0, 1.0]
diffuse = [1.0, 1.0, 1.0]
specular = [1.0, 1.0, 1.0]
shininess = 1.0

###################################################################################################
[[meshes]]
name = "at"

[[meshes]]
name = "door"

[[meshes]]
name = "teleporter"

[[meshes]]
name = "bar"

[[meshes]]
name = "house"

[[meshes]]
name = "hashtag"

[[meshes]]
name = "plus"

[[meshes]]
name = "O"

[[meshes]]
name = "T"

[[meshes]]
name = "cube"

[[meshes]]
name = "robot"

[[meshes]]
name = "stair_down"

[[meshes]]
name = "stair_up"

[[meshes]]
name = "tilde"

[[meshes]]
name = "equal"

[[meshes]]
name = "star"

[[meshes]]
name = "B"

########### ENTITY #############
[[entity]]
position = [8.0, 0.0, 8.0]
shader = "3d_pos_normal_color"
geometry = "mesh:at"
player = "player"
color = [1.0, 1.0, 1.0, 1.0]
ambient = [1.0, 1.0, 1.0]
diffuse = [1.0, 1.0, 1.0]
specular = [1.0, 1.0, 1.0]
shininess = 1.0

# SUN
[[entity]]
position = [0.0, 850.0, 0.0]
shader = "2dtexture"
geometry = "billboard:spherical"
scale = [650.0, 650.0, 650.0]
texture = "sun"
orbital = [1800.0, 1600.0, 0.0]
sun = [0.15, 1250.0]

# BLUE SUN
[[entity]]
position = [0.0, 850.0, 0.0]
shader = "2dtexture"
geometry = "billboard:spherical"
scale = [650.0, 650.0, 650.0]
texture = "sun_blue"
orbital = [1800.0, 1600.0, 3.1459]
sun = [0.15, 1250.0]

######### POINT LIGHTS
# LIGHT #0
[[entity]]
position = [5.0, 5.0, 5.0]
shader = "light"
geometry = "cube"
pointlight = [0.0, 0.0, 0.0]
scale = [0.4, 0.4, 0.4]

# LIGHT #1
[[entity]]
position = [35.0, 5.0, 35.0]
shader = "light"
geometry = "cube"
pointlight = [0.0, 0.0, 0.0]
scale = [0.4, 0.4, 0.4]

# LIGHT #2
[[entity]]
position = [5.0, 5.0, 35.0]
shader = "light"
geometry = "cube"
pointlight = [0.0, 0.0, 0.0]
scale = [0.4, 0.4, 0.4]

###################################################################################################
[[entity]]
position = [-5.0, -2.0, 0.0]
shader = "3dcube_texture"
geometry = "cube"
texture = "boring_cube"
random_junk_from_file = true

[[entity]]
position = [-5.0, 0.0, -2.0]
shader = "3dcube_texture"
geometry = "cube"
skybox = true
texture = "building_skybox"

[[entity]]
position = [20.0, 0.0, 20.0]
shader = "3dtexture"
geometry = "mesh:house"
texture = "TextureAtlas"
scale = [0.4, 0.4, 0.4]
random_junk_from_file = true
