title = "Level 0"
camera_spherical_coords = [2.56, 6.6446330, 56.379040]

ambient = [0.0, 0.0, 0.0]
directional_light_diffuse = [1.0, 1.0, 0.0]
directional_light_specular = [1.0, 1.0, 1.0]
directional_light_direction = [1.0, 1.0, 1.0]

[[resource]]
name = "building_skybox"
type = "texture:3dcube-RGB"
front = "assets/skybox/greenhaze_back.png"
right = "assets/skybox/greenhaze_right.png"
back = "assets/skybox/greenhaze_front.png"
left = "assets/skybox/greenhaze_left.png"
top = "assets/skybox/greenhaze_top.png"
bottom = "assets/skybox/greenhaze_bottom.png"

[[resource]]
name = "boring_cube"
type = "texture:3dcube-RGBA"
front = "assets/cube_front.jpg"
right = "assets/cube_right.jpg"
back = "assets/cube_back.jpg"
left = "assets/cube_left.jpg"
top = "assets/cube_top.jpg"
bottom = "assets/cube_bottom.jpg"

[[resource]]
name = "container"
type = "texture:2d-RGB"
filename = "assets/container.jpg"

[[resource]]
name = "Lava"
type = "texture:2d-RGBA"
filename = "assets/lava.jpg"

[[resource]]
name = "RedX"
type = "texture:2d-RGBA"
filename = "assets/redx.png"

[[resource]]
name = "InventorySlotEmpty"
type = "texture:2d-RGBA"
filename = "assets/ui/inventory_slot_empty.png"

[[resource]]
name = "wall"
type = "texture:2d-RGB"
filename = "assets/wall.jpg"

###################################################################################################
# HEIGHTMAPS
[[resource]]
name = "Area0-HM"
type = "texture:2d-RGBA"
filename = "assets/terrain/Area0-HM.png"
wrap = "clamp"

[[resource]]
name = "Area1-HM"
type = "texture:2d-RGBA"
filename = "assets/terrain/Area1-HM.png"
wrap = "clamp"

###################################################################################################
# TERRAIN TEXTURES
[[resource]]
name = "Floor0"
type = "texture:2d-RGBA"
filename = "assets/terrain/Floor0.png"
wrap = "repeat"

[[resource]]
name = "Grass0"
type = "texture:2d-RGB"
filename = "assets/terrain/Grass0.png"
wrap = "clamp"

[[resource]]
name = "TextureAtlas"
type = "texture:2d-RGB"
filename = "assets/TextureAtlas.jpg"
wrap = "clamp"

###########################
# WATER
[[resource]]
name = "Water-HM"
type = "texture:2d-RGBA"
filename = "assets/water/heightmap.png"
wrap = "clamp"

[[resource]]
name = "water-texture"
type = "texture:2d-RGBA"
filename = "assets/water/texture.png"
wrap = "mirror_repeat"

[[resource]]
name = "water-dudv"
type = "texture:2d-RGBA"
filename = "assets/water/dudv.png"

[[resource]]
name = "water-normal"
type = "texture:2d-RGBA"
filename = "assets/water/normal.png"
wrap = "clamp"

#############################'
# OTHER
[[resource]]
name = "gun"
type = "texture:2d-RGB"
filename = "assets/gun.png"

[[resource]]
name = "sword"
type = "texture:2d-RGB"
filename = "assets/sword.png"

[[resource]]
name = "cloud"
type = "texture:2d-RGBA"
filename = "assets/textures/cloud_cumulous_large.png"

[[resource]]
name = "sun"
type = "texture:2d-RGBA"
filename = "assets/textures/sun.png"

[[resource]]
name = "moon"
type = "texture:2d-RGBA"
filename = "assets/textures/Blendermoon1.png"

[[resource]]
name = "TorchUI"
type = "texture:2d-RGBA"
filename = "assets/ui/torch-icon.png"

[[resource]]
name = "TargetReticle"
type = "texture:2d-RGBA"
filename = "assets/circle_reticle.png"

[[resource]]
name = "NearbyTargetGlow"
type = "texture:2d-RGBA"
filename = "assets/textures/NearbyTargetGlow.png"

[[resource]]
name = "test_icon"
type = "texture:2d-RGB"
filename = "assets/test_icon.png"

###################################################################################################
[[tile]]
tile = "AT"
mesh = "at"
vshader = "3d_pos_normal_color"
color = [1.0, 1.0, 1.0, 1.0]
material = "player"

[[tile]]
tile = "BAR"
mesh = "bar"
vshader = "3d_pos_normal_color"
color = [1.0, 1.0, 1.0, 1.0]
material = "player"

[[tile]]
tile = "BRIDGE"
mesh = "equal"
vshader = "3d_pos_normal_color"
color = [1.0, 1.0, 1.0, 1.0]
material = "player"

[[tile]]
tile = "DOOR"
mesh = "door"
vshader = "3d_pos_normal_color"
color = [1.0, 1.0, 1.0, 1.0]
material = "player"

[[tile]]
tile = "FLOOR"
mesh = "plus"
vshader = "floor"
color = [1.0, 1.0, 1.0, 1.0]
material = "player"

[[tile]]
tile = "RIVER"
mesh = "tilde"
vshader = "river"
color = [1.0, 1.0, 1.0, 1.0]
material = "player"

[[tile]]
tile = "STAR"
mesh = "star"
vshader = "3d_pos_normal_color"
color = [1.0, 1.0, 1.0, 1.0]
material = "player"

[[tile]]
tile = "STAIR_DOWN"
mesh = "stair_down"
vshader = "stair"
color = [1.0, 1.0, 1.0, 1.0]
material = "player"

[[tile]]
tile = "STAIR_UP"
mesh = "stair_up"
vshader = "stair"
color = [1.0, 1.0, 1.0, 1.0]
material = "player"

[[tile]]
tile = "TELEPORTER"
mesh = "teleporter"
vshader = "3d_pos_normal_color"
color = [1.0, 1.0, 1.0, 1.0]
material = "player"

[[tile]]
tile = "WALL"
mesh = "hashtag"
vshader = "hashtag"
color = [1.0, 1.0, 1.0, 1.0]
material = "player"

###################################################################################################
[[meshes]]
name = "at"
path = "assets/"

[[meshes]]
name = "door"
path = "assets/"

[[meshes]]
name = "teleporter"
path = "assets/"

[[meshes]]
name = "bar"
path = "assets/"

[[meshes]]
name = "house"
path = "assets/"

[[meshes]]
name = "tree_lowpoly"
path = "assets/"

[[meshes]]
name = "hashtag"
path = "assets/"

[[meshes]]
name = "plus"
path = "assets/"

[[meshes]]
name = "O"
path = "assets/"

[[meshes]]
name = "T"
path = "assets/"

[[meshes]]
name = "cube"
path = "assets/"

[[meshes]]
name = "robot"
path = "assets/"

[[meshes]]
name = "stair_down"
path = "assets/"

[[meshes]]
name = "stair_up"
path = "assets/"

[[meshes]]
name = "tilde"
path = "assets/"

[[meshes]]
name = "equal"
path = "assets/"

[[meshes]]
name = "star"
path = "assets/"

[[meshes]]
name = "B"
path = "assets/"

########### FOG ################
[[fog]]
density = 0.007
gradient = 1.5
color = [0.0, 0.0, 0.0, 1.0]

########### ORBITAL DATA ###########
[[orbital-body]]
name = "sun"
x_radius = 1800.0
y_radius = 1200.00
z_radius = 1600.0

[[orbital-body]]
name = "moon"
x_radius = 1200.0
y_radius = 1200
z_radius = 1200.0
offset = 3.1459

########### ATTENUATION #############
[[attenuation]]
name = "default"
constant = 0.1
linear = 0.001
quadratic = 0.000001

[[attenuation]]
name = "nolight"
constant = 9999.0
linear = 9999.0
quadratic = 9999.0

[[attenuation]]
name = "moon"
constant = 0.1
linear = 0.001
quadratic = 9999.0

########### MATERIAL #############
[[material]]
name = "player"
ambient = [1.0, 1.0, 1.0]
diffuse = [1.0, 1.0, 1.0]
specular = [1.0, 1.0, 1.0]
shininess = 1.0

[[material]]
name = "terrain"
ambient = [1.0, 1.0, 1.0]
diffuse = [1.0, 1.0, 1.0]
specular = [1.0, 1.0, 1.0]
shininess = 1.0

[[material]]
name = "tree"
ambient = [0.0, 0.0, 1.0]
diffuse = [0.0, 0.0, 1.0]
specular = [0.0, 0.0, 1.0]
shininess = 10.00

[[material]]
name = "water"
ambient = [0.0, 0.0, 1.0]
diffuse = [0.0, 0.0, 1.0]
specular = [0.0, 0.0, 1.0]
shininess = 10.00

########### POINTLIGHT #############
[[pointlight]]
name = "moon"
attenuation = "nolight"
diffuse = [0.0, 0.0, 1.0]
specular = [0.0, 1.0, 0.0]

[[pointlight]]
name = "white"
attenuation = "nolight"
diffuse = [1.0, 1.0, 1.0]
specular = [1.0, 1.0, 1.0]

[[pointlight]]
name = "red"
attenuation = "nolight"
diffuse = [1.0, 0.0, 0.0]
specular = [1.0, 0.0, 0.0]

[[pointlight]]
name = "green"
attenuation = "nolight"
diffuse = [0.0, 1.0, 0.0]
specular = [0.0, 1.0, 0.0]

[[pointlight]]
name = "blue"
attenuation = "nolight"
diffuse = [0.0, 0.0, 1.0]
specular = [0.0, 0.0, 1.0]

########### ENTITY #############
[[entity]]
position = [8.0, 0.0, 8.0]
shader = "3d_pos_normal_color"
geometry = "mesh:at"
player = "player"
color = [1.0, 1.0, 1.0, 1.0]
material = "player"
name = "player"

[[entity]]
orbital-body = "sun"
position = [0.0, 850.0, 0.0]
shader = "2dtexture"
geometry = "billboard:spherical"
scale = [650.0, 650.0, 650.0]
texture = "sun"
name = "sun"

[[entity]]
orbital-body = "moon"
position = [0.0, 750.0, 0.0]
shader = "2dlight_uv"
geometry = "billboard:spherical"
scale = [650.0, 650.0, 650.0]
texture = "moon"
pointlight = "moon"
name = "Moon"

######### POINT LIGHTS
[[entity]]
name = "point light 0"
position = [2.0, 2.0, 2.0]
shader = "light"
geometry = "cube"
pointlight = "red"
scale = [0.4, 0.4, 0.4]

[[entity]]
name = "point light 1"
position = [4.0, 2.0, 2.0]
shader = "light"
geometry = "cube"
pointlight = "green"
scale = [0.4, 0.4, 0.4]

[[entity]]
name = "point light 2"
position = [4.0, 2.0, 4.0]
shader = "light"
geometry = "cube"
pointlight = "blue"
scale = [0.4, 0.4, 0.4]

[[entity]]
name = "point light 3"
position = [2.0, 2.0, 4.0]
shader = "light"
geometry = "cube"
pointlight = "white"
scale = [0.4, 0.4, 0.4]

############ SKYBOX
[[entity]]
name = "building skybox"
position = [0.0, 0.0, 0.0]
shader = "3dcube_texture"
geometry = "skybox"
texture = "building_skybox"

###################################################################################################
[[entity]]
name = "house"
material = "terrain"
position = [6.0, 1.0, 6.0]
shader = "3dtexture"
geometry = "mesh:house"
texture = "TextureAtlas"
scale = [0.4, 0.4, 0.4]
random_junk_from_file = true

[[entity]]
name = "tree"
material = "terrain"
position = [5.8, 0.5, 2.0]
shader = "3d_pos_normal_color"
geometry = "mesh:tree_lowpoly"
color = [1.0, 1.0, 1.0, 1.0]
scale = [3.0, 5.0, 3.0]
random_junk_from_file = true
