title = "Level 0"

[[resource]]
name = "building_skybox"
type = "texture:3dcube"
front = "sb_front.jpg"
right = "sb_right.jpg"
back = "sb_back.jpg"
left = "sb_left.jpg"
top = "sb_top.jpg"
bottom = "sb_bottom.jpg"

[[resource]]
name = "boring_cube"
type = "texture:3dcube"
front = "cube_front.jpg"
right = "cube_right.jpg"
back = "cube_back.jpg"
left = "cube_left.jpg"
top = "cube_top.jpg"
bottom = "cube_bottom.jpg"

[[resource]]
name = "container"
type = "texture:2d"
filename = "container.jpg"

[[resource]]
name = "wall"
type = "texture:2d"
filename = "wall.jpg"

[[resource]]
name = "TextureAtlas"
type = "texture:2d"
filename = "TextureAtlas.jpg"

################## MESHES #####################
[[meshes]]
name = "house"
normals = true
uvs = true

[[meshes]]
name = "hashtag"
normals = true
uvs = false
color = [1.000, 1.000, 1.000, 1.000]

[[meshes]]
name = "at"
normals = true
uvs = false
color = [1.000, 0.647, 0.000, 1.000] # ORANGE

[[meshes]]
name = "plus"
normals = true
uvs = false
color = [0.000, 0.000, 1.000, 1.000]

[[meshes]]
name = "O"
normals = true
uvs = false
color = [1.000, 0.000, 0.000, 1.000]

[[meshes]]
name = "T"
normals = true
uvs = false
color = [0.000, 1.000, 0.000, 1.000]

########### ENTITY #############
[[entity]]
pos = [2.0, 2.0, 0.0]
shader = "3d_pos_color"
color = [0.0, 0.8, 0.0, 0.7]
geometry = "cube"

[[entity]]
pos = [-4.0, 4.0, 0.0]
shader = "3d_pos_color"
color = [0.0, 0.0, 0.8, 0.4]
geometry = "cube"

[[entity]]
pos = [-5.0, -2.0, 0.0]
shader = "3dcube_texture"
geometry = "cube"
texture = "boring_cube"

[[entity]]
pos = [-5.0, 0.0, -2.0]
shader = "3dcube_texture"
geometry = "skybox"
texture = "building_skybox"

[[entity]]
pos = [2.0, -2.0, 2.0]
shader = "3dtexture"
geometry = "mesh:house"
texture = "TextureAtlas"

[[entity]]
pos = [0.0, 0.0, 2.0]
shader = "light"
geometry = "cube"
color = [0.0, 1.0, 0.0, 0.3]
light = "light"

[[entity]]
pos = [0.0, 0.0, 0.0]
shader = "3d_pos_normal_color"
geometry = "mesh:at"
# DOESN"T WORK UNTIL WE SET TEXTURES AFTER INITIAL MODEL HAS LOADED, UNTIL THEN THIS COLOR IS SET
# IN THE MESHES TABLE.
player = "player"

[[entity]]
pos = [-3.0, 0.0, -5.0]
shader = "3d_pos_normal_color"
geometry = "mesh:T"
# DOESN"T WORK UNTIL WE SET TEXTURES AFTER INITIAL MODEL HAS LOADED, UNTIL THEN THIS COLOR IS SET
# IN THE MESHES TABLE.
#color = [0.0, 1.0, 0.0, 1.0]

[[entity]]
pos = [3.0, 0.0, -5.0]
shader = "3d_pos_normal_color"
geometry = "mesh:O"
# DOESN"T WORK UNTIL WE SET TEXTURES AFTER INITIAL MODEL HAS LOADED, UNTIL THEN THIS COLOR IS SET
# IN THE MESHES TABLE.
#color = [0.0, 0.0, 1.0, 1.0]

[[entity]]
pos = [5.0, 0.0, -5.0]
shader = "3d_pos_normal_color"
geometry = "mesh:O"

# DOESN"T WORK UNTIL WE SET TEXTURES AFTER INITIAL MODEL HAS LOADED, UNTIL THEN THIS COLOR IS SET
# IN THE MESHES TABLE.
#color = [1.0, 0.0, 0.0, 1.0]
