title = "Level 0"
camera_spherical_coords = [2.56, 6.6446330, 56.379040]

[[global-lighting]]
ambient = [0.0, 0.0, 0.0]

[global-lighting.directional]
diffuse = [1.0, 1.0, 0.0]
specular = [1.0, 1.0, 1.0]
direction = [1.0, 1.0, 1.0]

########### FOG ################
[[fog]]
density = 0.007
gradient = 1.5
color = [1.0, 1.0, 1.0, 1.0]

########### ENTITY #############
[[entity]]
name = "sun"
position = [0.0, 850.0, 0.0]
shader = "billboard"
geometry = "billboard:spherical"
scale = [650.0, 650.0, 650.0]
#scale = [1.0, 1.0, 1.0]
texture = "sun"

[entity.orbital-body]
x = 1800.0
y = 1200.00
z = 1600.0

[[entity]]
name = "Moon"
position = [0.0, 750.0, 0.0]
shader = "2dlight_uv"
geometry = "billboard:spherical"
scale = [650.0, 650.0, 650.0]
#scale = [1.0, 1.0, 1.0]
texture = "moon"

[entity.pointlight]
attenuation = "nolight"
diffuse = [0.0, 0.0, 1.0]
specular = [0.0, 0.0, 1.0]

[entity.orbital-body]
x = 1200.0
y = 1200
z = 1200.0
offset = 3.1459

[[entity]]
name = "point light 0"
position = [2.0, 2.0, 2.0]
shader = "light"
geometry = "cube"
scale = [1.0, 1.0, 1.0]

[entity.cube_vertices]
min = [-1.0, -1.0, -1.0]
max = [ 1.0,  1.0,  1.0]

[entity.pointlight]
attenuation = "nolight"
diffuse = [1.0, 0.0, 0.0]
specular = [1.0, 0.0, 0.0]

[[entity]]
name = "point light 1"
position = [4.0, 2.0, 2.0]
shader = "light"
geometry = "cube"
scale = [1.0, 1.0, 1.0]

[entity.pointlight]
attenuation = "nolight"
diffuse = [0.0, 1.0, 0.0]
specular = [0.0, 1.0, 0.0]

[entity.cube_vertices]
min = [-1.5, -1.5, -1.5]
max = [ 1.5,  1.5,  1.5]

[[entity]]
name = "point light 2"
position = [4.0, 2.0, 4.0]
shader = "light"
geometry = "cube"
scale = [1.0, 1.0, 1.0]

[entity.pointlight]
attenuation = "nolight"
diffuse = [0.0, 0.0, 1.0]
specular = [0.0, 0.0, 1.0]

[entity.cube_vertices]
min = [-0.8, -0.8, -0.8]
max = [ 0.8,  0.8,  0.8]

[[entity]]
name = "point light 3"
position = [2.0, 2.0, 4.0]
shader = "light"
geometry = "cube"
scale = [1.0, 1.0, 1.0]

[entity.pointlight]
attenuation = "nolight"
diffuse = [1.0, 1.0, 1.0]
specular = [1.0, 1.0, 1.0]

[entity.cube_vertices]
min = [-0.4, -0.4, -0.4]
max = [ 0.4,  0.4,  0.4]

###################################################################################################
#[[entity]]
#name = "house"
#material = "terrain"
#position = [6.0, 1.0, 6.0]
#shader = "3dtexture"
#geometry = "mesh:house"
#texture = "TextureAtlas"
#scale = [5.0, 5.0, 5.0]
#random_junk_from_file = true

#[[entity]]
#name = "Tree0"
#material = "tree"
#position = [0.3, 0.0, 1.0]
#shader = "3d_pos_normal_color"
#geometry = "mesh:tree_lowpoly"
##scale = [15.0, 19.0, 8.0]
#scale = [1.0, 1.0, 1.0]
#random_junk_from_file = true

#[[entity]]
#name = "Tree1"
#material = "tree"
#position = [10.0, 0.0, 10.0]
#shader = "3d_pos_normal_color"
#geometry = "mesh:tree_lowpoly"
##scale = [20.0, 20.0, 12.0]
#scale = [1.0, 1.0, 1.0]
#random_junk_from_file = true

#[[entity]]
#name = "Tree2"
#material = "tree"
#position = [15.0, 1.0, 18.0]
#shader = "3d_pos_normal_color"
#geometry = "mesh:tree2"
##scale = [30.0, 30.0, 30.0]
#scale = [1.0, 1.0, 1.0]
#random_junk_from_file = true

#[[entity]]
#name = "Tree2"
#material = "tree"
#position = [40.0, 40.0, 40.0]
#shader = "3d_pos_normal_color"
#geometry = "mesh:tree2"
##scale = [40.0, 40.0, 40.0]
#scale = [1.0, 1.0, 1.0]
#random_junk_from_file = true
