title = "Level 0"
background = [0.0, 0.0, 0.0]
camera_spherical_coords = [2.56, 6.6446330, 56.379040]

ambient = [0.4, 0.33, 0.33]
directional_light_diffuse = [0.0, 0.0, 0.0]
directional_light_specular = [0.0, 0.0, 0.0]
directional_light_direction = [-1.0, 0.0, -1.0]

[[resource]]
name = "building_skybox"
type = "texture:3dcube-RGB"
front = "sb_front.jpg"
right = "sb_right.jpg"
back = "sb_back.jpg"
left = "sb_left.jpg"
top = "sb_top.jpg"
bottom = "sb_bottom.jpg"

[[resource]]
name = "boring_cube"
type = "texture:3dcube-RGB"
front = "cube_front.jpg"
right = "cube_right.jpg"
back = "cube_back.jpg"
left = "cube_left.jpg"
top = "cube_top.jpg"
bottom = "cube_bottom.jpg"

[[resource]]
name = "container"
type = "texture:2d-RGB"
filename = "container.jpg"

[[resource]]
name = "wall"
type = "texture:2d-RGB"
filename = "wall.jpg"

[[resource]]
name = "TextureAtlas"
type = "texture:2d-RGB"
filename = "TextureAtlas.jpg"

[[resource]]
name = "TargetReticle"
type = "texture:2d-RGBA"
filename = "circle_reticle.png"

###################################################################################################
[[tile]]
tile = "AT"
mesh = "at"
vshader = "3d_pos_normal_color"
color = [1.0, 1.0, 1.0]
ambient = [1.0, 1.0, 1.0]
diffuse = [1.0, 1.0, 1.0]
specular = [1.0, 1.0, 1.0]
shininess = 1.0

[[tile]]
tile = "BAR"
mesh = "bar"
vshader = "3d_pos_normal_color"
color = [1.0, 1.0, 1.0]
ambient = [1.0, 1.0, 1.0]
diffuse = [1.0, 1.0, 1.0]
specular = [1.0, 1.0, 1.0]
shininess = 1.0

[[tile]]
tile = "BRIDGE"
mesh = "equal"
vshader = "3d_pos_normal_color"
color = [1.0, 1.0, 1.0]
ambient = [1.0, 1.0, 1.0]
diffuse = [1.0, 1.0, 1.0]
specular = [1.0, 1.0, 1.0]
shininess = 1.0

[[tile]]
tile = "FLOOR"
mesh = "plus"
vshader = "floor"
color = [1.0, 1.0, 1.0]
ambient = [1.0, 1.0, 1.0]
diffuse = [1.0, 1.0, 1.0]
specular = [1.0, 1.0, 1.0]
shininess = 1.0

[[tile]]
tile = "RIVER"
mesh = "tilde"
vshader = "river"
color = [1.0, 1.0, 1.0]
ambient = [0.1, 0.2, 1.0]
diffuse = [0.1, 0.3, 1.0]
specular = [0.2, 0.4, 1.0]
shininess = 1.0

[[tile]]
tile = "STAR"
mesh = "star"
vshader = "3d_pos_normal_color"
color = [1.0, 1.0, 1.0]
ambient = [1.0, 1.0, 1.0]
diffuse = [1.0, 1.0, 1.0]
specular = [1.0, 1.0, 1.0]
shininess = 1.0

[[tile]]
tile = "STAIR_DOWN"
mesh = "stair_down"
vshader = "stair"
color = [1.0, 1.0, 1.0]
ambient = [0.0, 1.0, 0.0]
diffuse = [0.0, 1.0, 0.0]
specular = [0.0, 1.0, 0.0]
shininess = 1.0

[[tile]]
tile = "STAIR_UP"
mesh = "stair_up"
vshader = "stair"
color = [1.0, 1.0, 1.0]
ambient = [1.0, 0.0, 0.0]
diffuse = [1.0, 0.0, 0.0]
specular = [1.0, 0.0, 0.0]
shininess = 1.0

[[tile]]
tile = "WALL"
mesh = "hashtag"
vshader = "hashtag"
color = [1.0, 1.0, 1.0]
ambient = [1.0, 1.0, 1.0]
diffuse = [1.0, 1.0, 1.0]
specular = [1.0, 1.0, 1.0]
shininess = 1.0

###################################################################################################
[[meshes]]
name = "at"
colors = true
normals = true
uvs = false

[[meshes]]
name = "bar"
colors = true
normals = true
uvs = false

[[meshes]]
name = "house"
colors = false
normals = true
uvs = true

[[meshes]]
name = "hashtag"
colors = true
normals = true
uvs = false

[[meshes]]
name = "plus"
colors = true
normals = true
uvs = false

[[meshes]]
name = "O"
colors = true
normals = true
uvs = false

[[meshes]]
name = "O_no_normals"
colors = false
normals = false
uvs = false

[[meshes]]
name = "T"
colors = true
normals = true
uvs = false

[[meshes]]
name = "T_no_normals"
colors = false
normals = false
uvs = false

[[meshes]]
name = "cube"
colors = true
normals = true
uvs = false

[[meshes]]
name = "robot"
colors = true
normals = true
uvs = false

[[meshes]]
name = "stair_down"
colors = false
normals = true
uvs = false

[[meshes]]
name = "stair_up"
colors = false
normals = true
uvs = false

[[meshes]]
name = "tilde"
colors = false
normals = true
uvs = false

[[meshes]]
name = "equal"
colors = true
normals = true
uvs = false

[[meshes]]
name = "star"
colors = true
normals = true
uvs = false

[[meshes]]
name = "B"
colors = true
normals = true
uvs = false

########### ENTITY #############
[[entity]]
pos = [8.0, 0.0, 8.0]
shader = "3d_pos_normal_color"
geometry = "mesh:at"
player = "player"
color = [1.0, 1.0, 1.0]
ambient = [1.0, 1.0, 1.0]
diffuse = [1.0, 1.0, 1.0]
specular = [1.0, 1.0, 1.0]
shininess = 1.0

######### POINT LIGHTS
# LIGHT #0
[[entity]]
pos = [5.0, 5.0, 5.0]
shader = "light"
geometry = "cube"
pointlight = [0.0, 0.0, 0.0]
scale = [0.4, 0.4, 0.4]

# LIGHT #1
[[entity]]
pos = [35.0, 5.0, 35.0]
shader = "light"
geometry = "cube"
pointlight = [0.0, 0.0, 0.0]
scale = [0.4, 0.4, 0.4]

# LIGHT #2
[[entity]]
pos = [5.0, 5.0, 35.0]
shader = "light"
geometry = "cube"
pointlight = [0.0, 0.0, 0.0]
scale = [0.4, 0.4, 0.4]

###################################################################################################
[[entity]]
pos = [-5.0, -2.0, 0.0]
shader = "3dcube_texture"
geometry = "cube"
texture = "boring_cube"

[[entity]]
pos = [-5.0, 0.0, -2.0]
shader = "3dcube_texture"
geometry = "skybox"
texture = "building_skybox"

[[entity]]
pos = [20.0, 0.0, 20.0]
shader = "3dtexture"
geometry = "mesh:house"
texture = "TextureAtlas"
scale = [0.4, 0.4, 0.4]

[[entity]]
pos = [-3.0, 0.0, -5.0]
shader = "3d_pos_normal_color"
geometry = "mesh:T"
# DOESN"T WORK UNTIL WE SET TEXTURES AFTER INITIAL MODEL HAS LOADED, UNTIL THEN THIS COLOR IS SET
# IN THE MESHES TABLE.
#color = [0.0, 1.0, 0.0, 1.0]

[[entity]]
pos = [3.0, 0.0, -5.0]
shader = "3d_pos_normal_color"
geometry = "mesh:O"
# DOESN"T WORK UNTIL WE SET TEXTURES AFTER INITIAL MODEL HAS LOADED, UNTIL THEN THIS COLOR IS SET
# IN THE MESHES TABLE.
#color = [0.0, 0.0, 1.0, 1.0]

[[entity]]
pos = [5.0, 0.0, -5.0]
shader = "3d_pos_normal_color"
geometry = "mesh:O"
# DOESN"T WORK UNTIL WE SET TEXTURES AFTER INITIAL MODEL HAS LOADED, UNTIL THEN THIS COLOR IS SET
# IN THE MESHES TABLE.
#color = [1.0, 0.0, 0.0, 1.0]
