title = "Level 0"
camera_spherical_coords = [2.56, 6.6446330, 56.379040]

ambient = [0.0, 0.0, 0.0]
directional_light_diffuse = [1.0, 1.0, 0.0]
directional_light_specular = [1.0, 0.8, 0.0]
directional_light_direction = [1.0, 0.0, 0.1]

[[resource]]
name = "building_skybox"
type = "texture:3dcube-RGB"
front = "skybox/greenhaze_back.png"
right = "skybox/greenhaze_right.png"
back = "skybox/greenhaze_front.png"
left = "skybox/greenhaze_left.png"
top = "skybox/greenhaze_top.png"
bottom = "skybox/greenhaze_bottom.png"

[[resource]]
name = "boring_cube"
type = "texture:3dcube-RGBA"
front = "cube_front.jpg"
right = "cube_right.jpg"
back = "cube_back.jpg"
left = "cube_left.jpg"
top = "cube_top.jpg"
bottom = "cube_bottom.jpg"

[[resource]]
name = "container"
type = "texture:2d-RGB"
filename = "container.jpg"

[[resource]]
name = "Lava"
type = "texture:2d-RGBA"
filename = "lava.jpg"

[[resource]]
name = "RedX"
type = "texture:2d-RGBA"
filename = "redx.png"

[[resource]]
name = "InventorySlotEmpty"
type = "texture:2d-RGBA"
filename = "ui/inventory_slot_empty.png"

[[resource]]
name = "wall"
type = "texture:2d-RGB"
filename = "wall.jpg"

[[resource]]
name = "TextureAtlas"
type = "texture:2d-RGB"
filename = "TextureAtlas.jpg"

[[resource]]
name = "TerrainFloor"
type = "texture:2d-RGBA"
filename = "terrain/terrain-texture.png"
wrap = "clamp"

[[resource]]
name = "water"
type = "texture:2d-RGB"
filename = "terrain/water-texture.jpg"
wrap = "repeat"
uvs = 10000

[[resource]]
name = "gun"
type = "texture:2d-RGB"
filename = "gun.png"

[[resource]]
name = "sword"
type = "texture:2d-RGB"
filename = "sword.png"

[[resource]]
name = "cloud"
type = "texture:2d-RGBA"
filename = "textures/cloud_cumulous_large.png"

[[resource]]
name = "sun"
type = "texture:2d-RGBA"
filename = "textures/sun.png"

[[resource]]
name = "moon"
type = "texture:2d-RGBA"
filename = "textures/Blendermoon1.png"

[[resource]]
name = "TorchUI"
type = "texture:2d-RGBA"
filename = "ui/torch-icon.png"

[[resource]]
name = "TargetReticle"
type = "texture:2d-RGBA"
filename = "circle_reticle.png"

[[resource]]
name = "NearbyTargetGlow"
type = "texture:2d-RGBA"
filename = "textures/NearbyTargetGlow.png"

[[resource]]
name = "test_icon"
type = "texture:2d-RGB"
filename = "test_icon.png"

###################################################################################################
[[tile]]
tile = "AT"
mesh = "at"
vshader = "3d_pos_normal_color"
color = [1.0, 1.0, 1.0, 1.0]
material = "player"

[[tile]]
tile = "BAR"
mesh = "bar"
vshader = "3d_pos_normal_color"
color = [1.0, 1.0, 1.0, 1.0]
material = "player"

[[tile]]
tile = "BRIDGE"
mesh = "equal"
vshader = "3d_pos_normal_color"
color = [1.0, 1.0, 1.0, 1.0]
material = "player"

[[tile]]
tile = "DOOR"
mesh = "door"
vshader = "3d_pos_normal_color"
color = [1.0, 1.0, 1.0, 1.0]
material = "player"

[[tile]]
tile = "FLOOR"
mesh = "plus"
vshader = "floor"
color = [1.0, 1.0, 1.0, 1.0]
material = "player"

[[tile]]
tile = "RIVER"
mesh = "tilde"
vshader = "river"
color = [1.0, 1.0, 1.0, 1.0]
material = "player"

[[tile]]
tile = "STAR"
mesh = "star"
vshader = "3d_pos_normal_color"
color = [1.0, 1.0, 1.0, 1.0]
material = "player"

[[tile]]
tile = "STAIR_DOWN"
mesh = "stair_down"
vshader = "stair"
color = [1.0, 1.0, 1.0, 1.0]
material = "player"

[[tile]]
tile = "STAIR_UP"
mesh = "stair_up"
vshader = "stair"
color = [1.0, 1.0, 1.0, 1.0]
material = "player"

[[tile]]
tile = "TELEPORTER"
mesh = "teleporter"
vshader = "3d_pos_normal_color"
color = [1.0, 1.0, 1.0, 1.0]
material = "player"

[[tile]]
tile = "WALL"
mesh = "hashtag"
vshader = "hashtag"
color = [1.0, 1.0, 1.0, 1.0]
material = "player"

###################################################################################################
[[meshes]]
name = "at"
path = "assets/"

[[meshes]]
name = "door"
path = "assets/"

[[meshes]]
name = "teleporter"
path = "assets/"

[[meshes]]
name = "bar"
path = "assets/"

[[meshes]]
name = "house"
path = "assets/"

[[meshes]]
name = "hashtag"
path = "assets/"

[[meshes]]
name = "plus"
path = "assets/"

[[meshes]]
name = "O"
path = "assets/"

[[meshes]]
name = "T"
path = "assets/"

[[meshes]]
name = "cube"
path = "assets/"

[[meshes]]
name = "robot"
path = "assets/"

[[meshes]]
name = "stair_down"
path = "assets/"

[[meshes]]
name = "stair_up"
path = "assets/"

[[meshes]]
name = "tilde"
path = "assets/"

[[meshes]]
name = "equal"
path = "assets/"

[[meshes]]
name = "star"
path = "assets/"

[[meshes]]
name = "terrain"
path = "assets/terrain/"

[[meshes]]
name = "water"
path = "assets/terrain/"

[[meshes]]
name = "B"
path = "assets/"

########### FOG ################
[[fog]]
density = 0.007
gradient = 1.5
color = [0.0, 0.0, 0.0, 1.0]

########### ORBITAL DATA ###########
[[orbital-body]]
name = "sun"
x_radius = 1800.0
y_radius = 1200.00
z_radius = 1600.0

[[orbital-body]]
name = "moon"
x_radius = 1200.0
y_radius = 1200
z_radius = 1200.0
offset = 3.1459

########### ATTENUATION #############
[[attenuation]]
name = "default"
constant = 0.1
linear = 0.001
quadratic = 0.000001

[[attenuation]]
name = "nolight"
constant = 9999.0
linear = 9999.0
quadratic = 9999.0

[[attenuation]]
name = "moon"
constant = 0.1
linear = 0.001
quadratic = 9999.0

########### MATERIAL #############
[[material]]
name = "player"
ambient = [1.0, 1.0, 1.0]
diffuse = [1.0, 1.0, 1.0]
specular = [1.0, 1.0, 1.0]
shininess = 1.0

[[material]]
name = "terrain"
ambient = [1.0, 1.0, 1.0]
diffuse = [1.0, 1.0, 1.0]
specular = [1.0, 1.0, 1.0]
shininess = 1.0

[[material]]
name = "water"
ambient = [0.0, 0.0, 1.0]
diffuse = [0.0, 0.0, 1.0]
specular = [0.0, 0.0, 1.0]
shininess = 10.00

########### POINTLIGHT #############
[[pointlight]]
name = "moon"
attenuation = "nolight"
diffuse = [0.0, 0.0, 1.0]
specular = [0.0, 1.0, 0.0]

[[pointlight]]
name = "white"
attenuation = "nolight"
diffuse = [1.0, 1.0, 1.0]
specular = [1.0, 1.0, 1.0]

[[pointlight]]
name = "red"
attenuation = "nolight"
diffuse = [1.0, 0.0, 0.0]
specular = [1.0, 0.0, 0.0]

[[pointlight]]
name = "green"
attenuation = "nolight"
diffuse = [0.0, 1.0, 0.0]
specular = [0.0, 1.0, 0.0]

[[pointlight]]
name = "blue"
attenuation = "nolight"
diffuse = [0.0, 0.0, 1.0]
specular = [0.0, 0.0, 1.0]

########### ENTITY #############
[[entity]]
position = [8.0, 0.0, 8.0]
shader = "3d_pos_normal_color"
geometry = "mesh:at"
player = "player"
color = [1.0, 1.0, 1.0, 1.0]
material = "player"
name = "player"

[[entity]]
orbital-body = "sun"
position = [0.0, 850.0, 0.0]
shader = "2dtexture"
geometry = "billboard:spherical"
scale = [650.0, 650.0, 650.0]
texture = "sun"
name = "sun"

[[entity]]
orbital-body = "moon"
position = [0.0, 750.0, 0.0]
shader = "2dlight_uv"
geometry = "billboard:spherical"
scale = [650.0, 650.0, 650.0]
texture = "moon"
pointlight = "moon"
name = "Moon"

#[[entity]]
#position = [0.0, 0.0, 0.0]
#shader = "3dtexture"
#geometry = "mesh:terrain"
#texture = "TerrainFloor"
#scale = [1.0, 1.0, 1.0]
#terrain = true
#material = "terrain"
#name = "terrain0"

#[[entity]]
#position = [1.0, 0.0, 1.0]
#shader = "3dtexture"
#geometry = "mesh:terrain"
#texture = "TextureAtlas"
#scale = [2.0, 2.0, 2.0]
#terrain = true
#material = "terrain"
#name = "terrain1"

#[[entity]]
#position = [0.0, 88.0, 0.0]
#shader = "3dtexture"
#geometry = "mesh:water"
#material = "water"
#name = "water"
#scale = [1.0, 1.0, 1.0]
#texture = "water"
#water = true

######### POINT LIGHTS
[[entity]]
name = "point light 0"
position = [0.0, 5.0, 0.0]
shader = "light"
geometry = "cube"
pointlight = "red"
scale = [0.4, 0.4, 0.4]

[[entity]]
name = "point light 1"
position = [5.0, 5.0, 0.0]
shader = "light"
geometry = "cube"
pointlight = "green"
scale = [0.4, 0.4, 0.4]

[[entity]]
name = "point light 2"
position = [5.0, 5.0, 5.0]
shader = "light"
geometry = "cube"
pointlight = "blue"
scale = [0.4, 0.4, 0.4]

[[entity]]
name = "point light 3"
position = [0.0, 5.0, 5.0]
shader = "light"
geometry = "cube"
pointlight = "white"
scale = [0.4, 0.4, 0.4]

############ SKYBOX
[[entity]]
name = "building skybox"
position = [0.0, 0.0, 0.0]
shader = "3dcube_texture"
geometry = "skybox"
texture = "building_skybox"

###################################################################################################
[[entity]]
name = "house"
material = "terrain"
position = [20.0, 0.0, 20.0]
shader = "3dtexture"
geometry = "mesh:house"
texture = "TextureAtlas"
scale = [0.4, 0.4, 0.4]
random_junk_from_file = true
