#ifndef __PREAMBLE_GLSL__
#define __PREAMBLE_GLSL__

// vertex attribute indices
#define VERTEX_ATTRIBUTE_INDEX_OF_POSITION 0
#define VERTEX_ATTRIBUTE_INDEX_OF_COLOR 1
#define VERTEX_ATTRIBUTE_INDEX_OF_UV 2
#define VERTEX_ATTRIBUTE_INDEX_OF_NORMAL 3

#endif // __PREAMBLE_GLSL__
