#!/usr/bin/env bash
set -ex
source "scripts/common.bash"

cd ${BUILD}
cmake --build .
cd ..
${BUILD}/bin/build_postprocessing

# Place a link to the json database generated by clang into the source directory, so the clang
# tools can work.
ln -fs build-system/compile_commands.json .
