#!/usr/bin/env bash
set -ex
source "scripts/common-build.bash"

cd ${BUILD}
time cmake --build .
cd ..

${BUILD}/bin/BUILD_POSTPROCESSING

# Place a link to the json database generated by clang into the source directory, so the clang
# tools can work.
ln -fs build-system/compile_commands.json .
